name: Trigger auto deployment for aca-flask-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/aca-flask-app-AutoDeployTrigger-565ad984-1158-42d2-84b2-37114b0a4156.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrdemo0831private.azurecr.io
          username: ${{ secrets.ACAFLASKAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.ACAFLASKAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrdemo0831private.azurecr.io/flask-hello-world:${{ github.sha }}
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAFLASKAPP_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aca-flask-app -g aca-demo-0831 --server acrdemo0831private.azurecr.io --username  ${{ secrets.ACAFLASKAPP_REGISTRY_USERNAME }} --password ${{ secrets.ACAFLASKAPP_REGISTRY_PASSWORD }}
            az containerapp update -n aca-flask-app -g aca-demo-0831 --image acrdemo0831private.azurecr.io/flask-hello-world:${{ github.sha }}

  website-scan:
    runs-on: ubuntu-latest
    needs: deploy
    name: DAST (Dynamic Application Security Testing)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Action Full Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: owasp/zap2docker-stable
          target: ${{ secrets.WEBSITE_URL }}
          cmd_options: >
            -a
            -j
            -z "
            -config alert.maxInstances=0
            -config view.locale=ja_JP
            "
